### PR TITLE
Add support for a `Base` community member

### PR DESCRIPTION
**Pull request by skylineproject**
This is a quick attempt to sketch out one way that we could make adding oneself to the Community view as simple as:

- adding your image to `./src/images/community`
- adding your information to `./src/static/communityMembers.js`

I added myself in this format as an example (see f363ef7).

Some other things that could be added before the `WIP` tag is removed from this PR includes:

- [x] Updated directions to add yourself to the Community view
- [x] Changes so that image and component imports are more dynamic
- [x] Other fields we may want to add to the `communityMembers` file and display in `Base.js`

### CODE REVIEW

**Comment by experimatt** [comment]
This looks really good. If we can handle `<br />` tags within a `bio` text string in `communityMembers.js`, then I think we can do away with person-specific bio components.

This would limit the flexibility of being able to define your own bio, but as long as we've got the applicable FontAwesome icons pulled in, we'll be consistent about how we display bios on the site.

**Comment by skylineproject** [comment]
@experimatt I have another idea that might help a bit -- 

What if folks add two files to the repo:

`./src/images/community/${name}.png` with their image

`./src/components/community/${name}.js` which can have the following structure:

```
// ./src/components/community/BrandonJohnson.js 

export default {
  name: "Brandon Johnson", 
  ...,
  bio: "Hi, I'm Brandon."
}
```

So, `bio` can be a string, React Component, Node, whatever. I don't think we'll be able to intelligently parse JSX out of the string, that feels unpleasant to me. If the `bio` key is empty, we can default to something like we currently do.

Then, using some webpack shenanigans, we can require all files in the `community` dir, making that really easy-ish. We could even add a command that would generate this file for folks:

```sh
yarn community:add "Brandon Johnson"
```

**Comment by experimatt** [comment]
@skylineproject I'm with you up to this part
```
yarn community:add "Brandon Johnson"
```

...but I like where this is going.

What specifically would `yarn community:add` do? I'm a webpack novice, so I'm curious what you're thinking up

**Comment by skylineproject** [comment]
@experimatt This is what I'm thinking (in pseudo bash):

```sh
cp ./src/memberTemplate.js ./${name.js}
```

**Comment by experimatt** [comment]
Ohhhhhh so `yarn community:add` is just an alias/script to generate a new community member. that makes more sense, and could definitely work.

**Comment by experimatt** [comment]
@skylineproject wanna add Adriana's bio as a part of this PR? https://github.com/mplsjrdevs/mplsjrdevs/issues/62

**Comment by skylineproject** [comment]
@experimatt I think we're about ready to ship. Would you be willing to take a look at the instructions in the README and try adding Adrianna's bio? I'd love your feedback on that process.

**Pull request merged**
