### PR TITLE
colors for navbar

### PR DESCRIPTION
**Pull request by camckin10**

### CODE REVIEW

**Comment by experimatt** [comment]
Once you merge master into your branch and resolve the conflicts, this should be good to go!

**Comment by camckin10** [comment]
Hey Jenessa, this is ready for review again!

**Comment by experimatt** [comment]
This looks good to me -- we can continue working on making the navbar look exactly like Adriana's mockup once this gets merged in. Great work Chelsey!

**Comment by experimatt** [comment]
@camckin10 I'm merging this in for you!

**Pull request merged**
